## train stage 1
## trainer
run_train: True
num_epochs: 40
batch_size: 4
save_checkpoint_freq: 1
keep_num_checkpoint: 2
resume: True
use_logger: False
log_freq: 1000
archive_code: True
pretrain_dir: 'results/ckpts/clean_checkpoint.pth'
stage: 1

## dataloader
num_workers: 4
image_size: 64
training_data: ['celeba', 'casia_webface']
data_root: data/
K: 2
load_gt_depth: false

## model
exp_name: train_stage1 # exp_name
lr: 0.0001
loss_adv: true
lam_adv: 0.5
lam_shape: 0.3
lam_tex: 0.3
lam_light: 0.3
lam_perc: 1
view_constraint: True